cookbook/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories

  resources :ingredients_in_recipes

  resources :ingredients
  

  get 'site/index'

  devise_for :users
  resources :recipes

   root 'site#index'

end

cookbook/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

cookbook/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

cookbook/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :ingredients_in_recipes
  has_many :recipes, :through => :ingredients_in_recipes
end

cookbook/app/models/ingredients_in_recipe.rb
class IngredientsInRecipe < ActiveRecord::Base
  belongs_to :ingredient 
  belongs_to :recipe
end

cookbook/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  # ensure that a user_id is present
  validates :user_id, presence: true
=begin
  # ensure that title is present and at least 10 chars long
  validates :title, length: { minimum: 10 }, presence: true

  # ensure the url is present, and respects the URL format for http/https
  validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true
=end
  validates :name, presence: true
  validates :content, presence: true
  validates :preparing_time, presence: true
  validates :difficulty, presence: true
  
  has_many :ingredients_in_recipes
  has_many :ingredients, :through => :ingredients_in_recipes
  
  belongs_to :category
end

cookbook/app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

cookbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cookbook/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

cookbook/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @ingredients = Ingredient.all
    respond_with(@ingredients)
  end

  def show
    respond_with(@ingredient)
  end

  def new
    @ingredient = Ingredient.new
    respond_with(@ingredient)
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    respond_with(@ingredient)
  end

  def update
    @ingredient.update(ingredient_params)
    respond_with(@ingredient)
  end

  def destroy
    @ingredient.destroy
    respond_with(@ingredient)
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name, :calories, :protein, :carbohydrates, :fat)
    end
end

cookbook/app/controllers/ingredients_in_recipes_controller.rb
class IngredientsInRecipesController < ApplicationController
  before_action :set_ingredients_in_recipe, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @ingredients_in_recipes = IngredientsInRecipe.all
    respond_with(@ingredients_in_recipes)
  end

  def show
    respond_with(@ingredients_in_recipe)
  end

  def new
    @ingredients_in_recipe = IngredientsInRecipe.new
    respond_with(@ingredients_in_recipe)
  end

  def edit
  end

  def create
    @ingredients_in_recipe = IngredientsInRecipe.new(ingredients_in_recipe_params)
    @ingredients_in_recipe.save
    respond_with(@ingredients_in_recipe)
  end

  def update
    @ingredients_in_recipe.update(ingredients_in_recipe_params)
    respond_with(@ingredients_in_recipe)
  end

  def destroy
    @ingredients_in_recipe.destroy
    respond_with(@ingredients_in_recipe)
  end

  private
    def set_ingredients_in_recipe
      @ingredients_in_recipe = IngredientsInRecipe.find(params[:id])
    end

    def ingredients_in_recipe_params
      params.require(:ingredients_in_recipe).permit(:recipe_id, :ingredient_id, :amount)
    end
end

cookbook/app/controllers/my_sessions_controller.rb
class MySessionsController < ApplicationController
end

cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = current_user.recipes.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :content, :category_id, :preparing_time, :difficulty)
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      unless @recipe = current_user.recipes.where(id: params[:id]).first
        flash[:alert] = 'Recipe not found.'
        redirect_to root_url
      end
    end
end

cookbook/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

cookbook/app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = Recipe.order('created_at desc')
  end
end

cookbook/app/controllers/user_controller.rb
 
 class UserController < ApplicationController
   
 end

cookbook/app/helpers/application_helper.rb
module ApplicationHelper
end

cookbook/app/helpers/categories_helper.rb
module CategoriesHelper
end

cookbook/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

cookbook/app/helpers/ingredients_in_recipes_helper.rb
module IngredientsInRecipesHelper
end

cookbook/app/helpers/my_sessions_helper.rb
module MySessionsHelper
end

cookbook/app/helpers/recipes_helper.rb
module RecipesHelper
end

cookbook/app/helpers/sessions_helper.rb
module SessionsHelper
end

cookbook/app/helpers/site_helper.rb
module SiteHelper
end

cookbook/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cookbook/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category,class: 'btn btn-info btn-xs' %>
<%= link_to 'Back', categories_path, class: 'btn btn-info btn-xs' %>

cookbook/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

cookbook/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path, class: 'btn btn-success' %>

cookbook/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>



<table style="width: 100%">
<h1>Listing recipes in category: <%= @category.name %> </h1>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% Recipe.select {|recipe| recipe.category_id == @category.id}.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.name, controller: "recipes", action: "show", id: recipe.id %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_category_path(@category),class: 'btn btn-info btn-xs' %>
<%= link_to 'Back', categories_path, class: 'btn btn-info btn-xs' %>

cookbook/app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="field">
    <%= f.label :protein %><br>
    <%= f.number_field :protein %>
  </div>
  <div class="field">
    <%= f.label :carbohydrates %><br>
    <%= f.number_field :carbohydrates %>
  </div>
  <div class="field">
    <%= f.label :fat %><br>
    <%= f.number_field :fat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cookbook/app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

cookbook/app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Calories</th>
      <th>Protein</th>
      <th>Carbohydrates</th>
      <th>Fat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.calories %></td>
        <td><%= ingredient.protein %></td>
        <td><%= ingredient.carbohydrates %></td>
        <td><%= ingredient.fat %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

cookbook/app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path, class: 'btn btn-info btn-xs' %>

cookbook/app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @ingredient.calories %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @ingredient.protein %>
</p>

<p>
  <strong>Carbohydrates:</strong>
  <%= @ingredient.carbohydrates %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @ingredient.fat %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

cookbook/app/views/ingredients_in_recipes/_form.html.erb
<%= form_for(@ingredients_in_recipe) do |f| %>
  <% if @ingredients_in_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredients_in_recipe.errors.count, "error") %> prohibited this ingredients_in_recipe from being saved:</h2>

      <ul>
      <% @ingredients_in_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.collection_select :recipe_id, Recipe.all, :id, :name, {}, {:class=>'input', :name=>'normalSelect', :id=>'normalSelect', :style=>'width:75%', :style=>'background-color:#9999ff', :onchange=>"$('#accordion').accordion('activate',2);$('#blind').show('blind', 500)"} %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br> 
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name, {}, {:class=>'input', :name=>'normalSelect', :id=>'normalSelect', :style=>'width:75%', :style=>'background-color:#9999ff', :onchange=>"$('#accordion').accordion('activate',2);$('#blind').show('blind', 500)"}%>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
  <%= link_to 'New ingredient', new_ingredient_path, class: 'btn btn-info btn-xs' %>
<% end %>

cookbook/app/views/ingredients_in_recipes/edit.html.erb
<h1>Editing Ingredients In Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredients_in_recipe %> |
<%= link_to 'Back', ingredients_in_recipes_path %>

cookbook/app/views/ingredients_in_recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ingredients In Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients_in_recipes.each do |ingredients_in_recipe| %>
      <tr>
        <td><%= ingredients_in_recipe.recipe_id %></td>
        <td><%= ingredients_in_recipe.ingredient_id %></td>
        <td><%= ingredients_in_recipe.amount %></td>
        <td><%= link_to 'Show', ingredients_in_recipe %></td>
        <td><%= link_to 'Edit', edit_ingredients_in_recipe_path(ingredients_in_recipe) %></td>
        <td><%= link_to 'Destroy', ingredients_in_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredients in recipe', new_ingredients_in_recipe_path %>

cookbook/app/views/ingredients_in_recipes/new.html.erb
<h1>New Ingredients In Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_in_recipes_path, class: 'btn btn-info btn-xs' %>

cookbook/app/views/ingredients_in_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredients_in_recipe.recipe_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @ingredients_in_recipe.ingredient_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @ingredients_in_recipe.amount %>
</p>

<%= link_to 'Edit', edit_ingredients_in_recipe_path(@ingredients_in_recipe) %> |
<%= link_to 'Back', ingredients_in_recipes_path %>

cookbook/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {}, {:class=>'input', :name=>'normalSelect', :id=>'normalSelect', :style=>'width:75%', :style=>'background-color:#9999ff', :onchange=>"$('#accordion').accordion('activate',2);$('#blind').show('blind', 500)"} %>
  </div> 
  <div class="field">
    <%= f.label :preparing_time %><br>
    <%= f.number_field :preparing_time %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Add ingredients', new_ingredients_in_recipe_path,class: 'btn btn-info btn-xs' %>
<% end %>

cookbook/app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

cookbook/app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Category</th>
      <th>Preparing time</th>
      <th>Difficulty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.content %></td>
        <td><%= Category.find_by_id(recipe.category_id).name %></td>
        <td><%= recipe.preparing_time %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= link_to 'Show', recipe, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe),class: 'btn btn-info btn-xs'%></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_recipe_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Recipe
<% end %>

cookbook/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path,class: 'btn btn-info btn-xs' %>

cookbook/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @recipe.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find_by_id(@recipe.category_id).name%>
</p>

<p>
  <strong>Preparing time:</strong>
  <%= @recipe.preparing_time %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @recipe.difficulty %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>